### ISSUE TITLE
Recipe Book outdated/not working?

### ISSUE THREAD

**Issue by luckybgit** [tabarra/PlumeESX-recipe#19]
Im hosting it on a Linux server at home. ( can run other templates from txAdmin )

To Recreate my Problem:

Reset the Current txAdmin Instance 
Choose Popular Themes -> PlumeESX-legacy -> leave everything else default. I added my cfx_key and "customized" my database connection (just added a dedicated user not run as root)

It will "instantly" crash at   "# Download and prepare server.cfg / loadingscreen / database"
I fixed this by cloning the Repo myself and copy the files under txData/PlumeESXLegacy_(weirdnumbers).base/tmp/plume_esx
Basically did the work for the Recipe Book.

Then it crashes at:
  - action: replace_string
    file: ./resources/[hud]/cosmo_hud/config.lua
    search: 'Config.AlwaysShowRadar = false'
    replace: 'Config.AlwaysShowRadar = true'
    
 I commented that one out on my next run and it worked without any errors.

But now I have weird file names and the server does not start.
![plume_esx](https://user-images.githubusercontent.com/37333947/138316829-23421125-b20a-4e43-88b5-216fa14d84fa.png)

and some of the folders or many folders to be specific are empty.

I also tried to "copy" the Recipe Book by hand but at some point it asked for my Github credentials. Could that be a problem?

txAdmin version: 4.6.1
FXServer build: 4821

Im also new to FiveM Servers in general. Sorry if it is something obvious.

**Comment by tabarra** [comment]
Plume has been retired.
