### ISSUE TITLE
need to nominally only start some resources

### ISSUE THREAD

**Issue by tabarra** [tabarra/PlumeESX-recipe#20]
https://github.com/tabarra/PlumeESX-recipe/blob/1813c463157fcc6f8f21ec09aa1b561e592e2a8d/server.cfg#L41

**Comment by Hamy-os** [comment]
do you want me to only start the necessary ones instead of the whole folder? I just did this so people can understand they can do this to avoid them cluttering their cfg file when they are expanding upon this recipe

**Comment by tabarra** [comment]
fixed it already
