### ISSUE TITLE
I have 2 Problems :(

### ISSUE THREAD

**Issue by FritLP** [tabarra/PlumeESX-recipe#22]
Good day, 
I have the problem that on my Plume ESX server, when I insert farm routes, I can collect something only once and then supposedly my inventory is full, although I still have enough space, so for example 1/500 (I tried several different scripts and always the same problem). Also, in the HUD the cash does not update (tried many different ones), only when reconnecting. I tried both things also on empty ESX servers, because I thought it was because of other resources, but there it doesn't work either.

best wishes

**Comment by tabarra** [comment]
Plume has been retired.
