### ISSUE TITLE
Jobs not working

### ISSUE THREAD

**Issue by Demonith** [tabarra/PlumeESX-recipe#5]
Some od jobs not working or they are buged wont show the work or when u go to mark it cant do nothing shows nothing 
for now i tested Miner Butcher also mechanic is broken

**Comment by FBFezz** [comment]
do you go to the locker room and change into the work clothes?

**Comment by Hamy-os** [comment]
@tabarra close these issues as they are for v1-final version of plume and new one is in legacy
