### ISSUE TITLE
es_extended deleted from Github

### ISSUE THREAD

**Issue by Scottywonderful** [tabarra/PlumeESX-recipe#9]
Hey there @tabarra,

I tried installing this via the TxAdmin deployer but kept failing at section 17 which is this:

```
   # Download ESX resources
   - action: download_github
     src: https://github.com/esx-framework/es_extended
     ref: 694cd6757802c432bd025f8251dee33760080eff
     dest: ./resources/[esx]/es_extended
```

With that being said I believe this needs to be updated with a new link due to it being deleted/removed from github.
To help, I have found 2 forked githubs which have been updated only 14 and 15 months ago..

First one found was this: [https://github.com/esx-community/es_extended](https://github.com/esx-community/es_extended)

Second one I found was this: [https://github.com/Ereshkinyan/es_extended](https://github.com/Ereshkinyan/es_extended)

Hope this helps and could be possibly fixed quickly.
Thanks,
Scotty

**Comment by Hamy-os** [comment]
the repo is removed. Please wait while we make a new recipe

**Comment by Scottywonderful** [comment]
Sorry should have explained that this is in your Receipe.yaml file

Link to raw:
[https://raw.githubusercontent.com/tabarra/PlumeESX-recipe/main/recipe.yaml](https://raw.githubusercontent.com/tabarra/PlumeESX-recipe/main/recipe.yaml)

**Comment by Hamy-os** [comment]
Feel free to help update it here https://github.com/tabarra/PlumeESX-recipe/pull/8

**Comment by Scottywonderful** [comment]
> Feel free to help update it here #8

Thanks, I would do an edit though I just keep getting this message:

> This pull request is still a work in progress
> Only those with write access to this repository can mark a draft pull request as ready for review.

**Comment by Hamy-os** [comment]
> ```
>  This pull request is still a work in progress
>  Only those with write access to this repository can mark a draft pull request as ready for review.
> ```

just make a comment with the change you want and ill commit it then :P

**Comment by Scottywonderful** [comment]
> > ```
> >  This pull request is still a work in progress
> >  Only those with write access to this repository can mark a draft pull request as ready for review.
> > ```
> 
> just make a comment with the change you want and ill commit it then :P

Done it, I see that your commit removes it anyway and lets it focus on [https://github.com/esx-framework/esx-legacy](https://github.com/esx-framework/esx-legacy) which is actually a great idea and I believe should be approved.

**Comment by Scottywonderful** [comment]
Closing ticket as Pull Request #8 removes this link and updates all the links to be one major link referencing [https://github.com/esx-framework/esx-legacy](https://github.com/esx-framework/esx-legacy).

This will resolve this issue if that pull request is approved.
